//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> ( field_modifier() )*
 * f1 -> Type()
 * f2 -> <IDENTIFIER>
 * f3 -> field_body()
 */
public class FieldDeclaration implements Node {
   public NodeListOptional f0;
   public Type f1;
   public NodeToken f2;
   public field_body f3;

   public FieldDeclaration(NodeListOptional n0, Type n1, NodeToken n2, field_body n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

