//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> ( "abstract" | "public" )*
 * f1 -> "interface"
 * f2 -> <IDENTIFIER>
 * f3 -> [ "extends" NameList() ]
 * f4 -> "{"
 * f5 -> ( InterfaceMemberDeclaration() )*
 * f6 -> "}"
 */
public class InterfaceDeclaration implements Node {
   public NodeListOptional f0;
   public NodeToken f1;
   public NodeToken f2;
   public NodeOptional f3;
   public NodeToken f4;
   public NodeListOptional f5;
   public NodeToken f6;

   public InterfaceDeclaration(NodeListOptional n0, NodeToken n1, NodeToken n2, NodeOptional n3, NodeToken n4, NodeListOptional n5, NodeToken n6) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
   }

   public InterfaceDeclaration(NodeListOptional n0, NodeToken n1, NodeOptional n2, NodeListOptional n3) {
      f0 = n0;
      f1 = new NodeToken("interface");
      f2 = n1;
      f3 = n2;
      f4 = new NodeToken("{");
      f5 = n3;
      f6 = new NodeToken("}");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

