//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> Type()
 * f1 -> VariableDeclarator()
 * f2 -> ( "," VariableDeclarator() )*
 */
public class LocalVariableDeclaration implements Node {
   public Type f0;
   public VariableDeclarator f1;
   public NodeListOptional f2;

   public LocalVariableDeclaration(Type n0, VariableDeclarator n1, NodeListOptional n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

