//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.*;



public class MyVisitor extends DepthFirstVisitor {
   private String output;

   public MyVisitor() {
      output = "";
   }

   public void visit(ClassDeclaration n) {
      String la = "";
      la += n.f0.nodes.get(0).toString();
      la += n.f1.toString();
//      la += n.f2.toString();
//      la += n.f3.toString();
//      la += n.f4.toString();
//      la += n.f5.toString();
//      la += n.f6.toString();
//      la += n.f7.toString();
      output += la;
//      System.out.println(la);
      output += n.f1.toString();
   }

//   public void visit(TypeDeclaration n) {
//      n.f0.accept(this);
//   }


   public void writeOutputToFile() throws IOException {
      String path = "cgol3_output.java";
      Files.write( Paths.get(path), output.getBytes());
   }

}
